window.RosterProSeed = {
  brand: {
    toolName: "RosterPro",
    clinicName: "Stetho MD",
    poweredBy: "Help360 MD",
    supportPhone: "(321) 999-9553",
    tagline: "Schedule. Manage. Empower.",
    assets: {
      clinicLogo: "assets/stetho-md.jpg",
      partnerLogo: "assets/help360-md.png",
      productLogo: "assets/rosterpro-logo.jpg"
    }
  },
  defaultMonth: "2026-06",
  defaultLocation: "Tampa",
  localAccounts: [
    {
      username: "umazhar",
      fullName: "Usama Mazhar",
      role: "Administrator",
      staffId: "ST-031",
      passwordHash: "d7bb9288f9bd001f849ba48d75004c05f1a7de146f96dedb748e792ca1ef2bfc",
      status: "Active"
    },
    {
      username: "frahman14",
      fullName: "Farhana Rahman",
      role: "Administrator",
      staffId: "ST-023",
      passwordHash: "58ea53aa753312d7d1ef6a7499b1605f2b634deb112a5604b41c49f6e3879b56",
      status: "Active"
    },
    {
      username: "fkanwal1",
      fullName: "Fozia Kanwal",
      role: "Administrator",
      staffId: "ST-034",
      passwordHash: "dcbc4d8c9848d6bdcfa820975193de6a99f15da2c58f88feb2438403024a8f3e",
      status: "Active"
    },
    {
      username: "cmohammad1",
      fullName: "Muhammad Asman",
      role: "Administrator",
      staffId: "ST-020",
      passwordHash: "55412b95ac2612e2db117b3ffb4822630f170b8b16e4b5f59cd74dc7d2525b1f",
      status: "Active"
    }
  ],
  locations: [
    {
      id: "LOC-TAMPA",
      name: "Tampa",
      address: "",
      phoneNumber: "(813) 666-2701",
      timeZone: "EST",
      manager: "Sabiha Sikder",
      printNote: "Sabiha Office Team Lead Mondays through Thursdays 8:00AM to 6:00PM"
    },
    {
      id: "LOC-ZEPHYRHILLS",
      name: "Zephyrhills",
      address: "",
      phoneNumber: "(813) 212-6639",
      timeZone: "EST",
      manager: "Muhammad Asman",
      printNote: "Monday to Friday - 7:30AM to 6PM, Saturday - 7:30AM to 2PM (Everyday Wednesday Dr. Rahman - Tampa)"
    },
    {
      id: "LOC-REMOTE",
      name: "Remote",
      address: "",
      phoneNumber: "(321) 999-9553",
      timeZone: "EST",
      manager: "Fozia Kanwal",
      printNote: "Remote staff schedule varies by department."
    }
  ],
  staff: [
    {
      staffId: "ST-001",
      fullName: "Rajeshwari Borkar",
      email: "rajeshwari.borkar@stethomd.com",
      phoneNumber: "(813) 666-2701",
      extension: "103",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-09",
      preferredWorkingDays: "Tampa volunteer days",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa",
      athenaUser: "rborkar",
      notes: "Tampa (Volunteer): June 1, 3, 6, 8, 13, 15, 20, 22, 27, 29. Appears as Rajeshwary.",
      strengths: "Volunteer support",
      schedulingPreferences: "Volunteer coverage",
      specialInstructions: ""
    },
    {
      staffId: "ST-002",
      fullName: "Jennifer Chirino",
      email: "jennifer.chirino@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-23",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "jchirino1",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-003",
      fullName: "Rayhaan Chowdhury",
      email: "rayhaan.chowdhury@stethomd.com",
      phoneNumber: "(813) 710-3024",
      extension: "205",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "rchowdhury12",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-004",
      fullName: "Alyssa Dolotina",
      email: "Alyssa.Dolotina@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-04-15",
      preferredWorkingDays: "June 9",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "adolotina",
      notes: "Zephyrhills: June 9.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-005",
      fullName: "Jessica Killeen",
      email: "jessica.killeen@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-23",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "jkilleen9",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-006",
      fullName: "Ashton Mcgriff",
      email: "ashton.mcgriff@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-04-15",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "amcgriff6",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-007",
      fullName: "Ezinne Nwoye",
      email: "ezinne.nwoye@stethomd.com",
      phoneNumber: "(813) 666-2701",
      extension: "103",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-09",
      preferredWorkingDays: "Tampa June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa",
      athenaUser: "enwoye",
      notes: "Tampa: June 2, 3, 4, 10, 11, 12, 17, 18, 19, 22, 26, 28.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-008",
      fullName: "Samaya Paris",
      email: "Samaya.Paris@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-23",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "sparis22",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-009",
      fullName: "Melissa Reimert",
      email: "melissa.reimert@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-23",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "mreimert",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-010",
      fullName: "Gabriel Renato",
      email: "gabriel.renato@stethomd.com",
      phoneNumber: "(813) 709-8572",
      extension: "105",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-04-15",
      preferredWorkingDays: "Tampa and Zephyrhills June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa, Zephyrhills",
      athenaUser: "grenato",
      notes: "Zephyrhills: June 2, 4, 5, 6, 9, 11, 12, 13, 16, 18, 19, 20, 23, 25, 26, 27, 30. Appears as Gabi. Tampa: June 5, 6, 7, 13, 14, 20, 21, 27, 28. Appears as Gabriel.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-011",
      fullName: "Sabiha Sikder",
      email: "sabiha.sikder@stethomd.com",
      phoneNumber: "(813) 666-2701",
      extension: "103",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2022-10-26",
      preferredWorkingDays: "Office lead Monday through Thursday",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa",
      athenaUser: "ssikder2",
      notes: "Tampa Office Lead: June 1, 3, 4, 5, 8, 10, 11, 12, 15, 16, 18, 21, 22, 23, 24, 25, 29. Appears as Sabiha.",
      strengths: "Office lead",
      schedulingPreferences: "Mondays through Thursdays 8:00AM to 6:00PM",
      specialInstructions: ""
    },
    {
      staffId: "ST-012",
      fullName: "Shana Wiggins",
      email: "shana.wiggins@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Clinical Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-09",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "swiggins54",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-013",
      fullName: "Lilian Adams",
      email: "Lilian.Adams@stethomd.com",
      phoneNumber: "(813) 666-2701",
      extension: "103",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Front Desk Staff",
      department: "Front Desk",
      primarySpecialty: "None",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "Tampa weekend coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa",
      athenaUser: "ladams294",
      notes: "Tampa: June 2, 6, 7, 13, 14, 20, 21, 27, 28, 30.",
      strengths: "Front desk",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-014",
      fullName: "Luna Dalay Caraballo Suarez",
      email: "luna-dalay.caraballo-suarez@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Front Desk Staff",
      department: "Front Desk",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-23",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "lcaraballosuarez",
      notes: "Not listed on June schedule.",
      strengths: "Front desk",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-015",
      fullName: "Krish Adhikari",
      email: "Krish.Adhikari@stethomd.com",
      phoneNumber: "(813) 710-3024",
      extension: "205",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Nurse Practitioner",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-02-24",
      preferredWorkingDays: "Zephyrhills June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "kadhikari4",
      notes: "Zephyrhills: June 3, 4, 12, 13, 17, 18, 22, 23, 26, 27. Appears as Krish.",
      strengths: "Nurse practitioner",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-016",
      fullName: "Shameka Herring",
      email: "shameka.herring@stethomd.com",
      phoneNumber: "(813) 709-8572",
      extension: "105",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Nurse Practitioner",
      department: "Clinical",
      primarySpecialty: "Nurse Practitioner, Family",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "Tampa June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa",
      athenaUser: "sherring38",
      notes: "Tampa: June 1, 2, 5, 8, 9, 13, 14, 15, 16, 19, 22, 23, 27, 28, 29, 30. Appears as Shameka.",
      strengths: "Nurse practitioner",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-017",
      fullName: "Camila McCalen",
      email: "camila.cachon@stethomd.com",
      phoneNumber: "(813) 709-8572",
      extension: "105",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Nurse Practitioner",
      department: "Clinical",
      primarySpecialty: "Family Medicine",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2025-06-09",
      preferredWorkingDays: "Tampa and Zephyrhills June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa, Zephyrhills",
      athenaUser: "cchacon15",
      notes: "Zephyrhills: June 1, 15, 29. Tampa: June 3, 4, 6, 7, 10, 11, 12, 17, 18, 20, 21, 24, 25, 26, 27, 28, 29. Appears as Camilla or Camila.",
      strengths: "Nurse practitioner",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-018",
      fullName: "Easton Savery",
      email: "easton.savery@stethomd.com",
      phoneNumber: "(813) 710-3024",
      extension: "205",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Nurse Practitioner",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-09",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "esavery",
      notes: "Not listed on June schedule.",
      strengths: "Nurse practitioner",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-019",
      fullName: "Latoya Woods-Williams",
      email: "latoya.woods-williams@stethomd.com",
      phoneNumber: "(813) 212-6639",
      extension: "203",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Nurse Practitioner",
      department: "Clinical",
      primarySpecialty: "Internal Medicine",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-23",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "Latoya Woods-Williams",
      notes: "Email was truncated in the provided PDF; completed from visible name convention.",
      strengths: "Nurse practitioner",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-020",
      fullName: "Muhammad Asman",
      email: "asman.mohammad@stethomd.com",
      phoneNumber: "(813) 776-1666",
      extension: "110",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Office Manager",
      department: "Administration",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-02-24",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "cmohammad1",
      notes: "Permanent administrator.",
      strengths: "Office management",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-021",
      fullName: "Josephine Vargas",
      email: "josephine.vargas@stethomd.com",
      phoneNumber: "(813) 448-7752",
      extension: "109",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Office Manager",
      department: "Administration",
      primarySpecialty: "None",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-02-24",
      preferredWorkingDays: "Zephyrhills June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "jvargas218",
      notes: "Zephyrhills: June 1, 2, 8, 9, 15, 16, 22, 23, 29, 30. Appears as Josephine.",
      strengths: "Office management",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-022",
      fullName: "Abdul Ghani",
      email: "abdul.ghani@stethomd.com",
      phoneNumber: "(813) 710-3024",
      extension: "205",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Physician",
      department: "Provider",
      primarySpecialty: "Internal Medicine",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-02-24",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "aghani4",
      notes: "Not listed on June schedule.",
      strengths: "Internal medicine",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-023",
      fullName: "Farhana Rahman",
      email: "farhana.rahman@stethomd.com",
      phoneNumber: "(813) 397-8512",
      extension: "101",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Physician",
      department: "Provider",
      primarySpecialty: "Family Medicine",
      officeLocation: "Zephyrhills",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2025-06-09",
      preferredWorkingDays: "Zephyrhills June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Zephyrhills",
      athenaUser: "frahman14",
      notes: "Zephyrhills: June 2, 5, 6, 8, 9, 10, 11, 16, 19, 20, 24, 25, 30. Appears as Dr. Rahman. Permanent administrator.",
      strengths: "Front Desk, Insurance Verification, Referrals, Appointment Scheduling, Phone Management, Family medicine",
      schedulingPreferences: "Front Desk, Insurance Verification, Referrals, Appointment Scheduling, Phone Management",
      specialInstructions: "Skill Level: Insurance Verification - Expert; Referrals - Advanced; Scheduling - Expert"
    },
    {
      staffId: "ST-024",
      fullName: "Ofozoba Chibuike",
      email: "Ofozoba.Chibuike@stethomd.com",
      phoneNumber: "(813) 499-9300",
      extension: "107",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Scribe",
      department: "Remote",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2025-06-09",
      preferredWorkingDays: "Monday-Saturday",
      preferredShiftTime: "8:00 AM - 2:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "ochibuike",
      notes: "Remote scribe schedule: Monday-Saturday.",
      strengths: "Scribe",
      schedulingPreferences: "Monday-Saturday",
      specialInstructions: ""
    },
    {
      staffId: "ST-025",
      fullName: "Benedicta Chidalu",
      email: "benedicta.chidalu@stethomd.com",
      phoneNumber: "(813) 544-5500",
      extension: "108",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Scribe",
      department: "Remote",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-04-15",
      preferredWorkingDays: "Monday-Saturday",
      preferredShiftTime: "8:00 AM - 2:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "bchidalu",
      notes: "Remote scribe schedule: Monday-Saturday.",
      strengths: "Scribe",
      schedulingPreferences: "Monday-Saturday",
      specialInstructions: ""
    },
    {
      staffId: "ST-026",
      fullName: "Allycia Estrellas",
      email: "allycia.estrellas@stethomd.com",
      phoneNumber: "(813) 666-2701",
      extension: "103",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "Not listed on June schedule",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa",
      athenaUser: "aestrellas",
      notes: "Not listed on June schedule.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-027",
      fullName: "Lucy Yzabelle Luklukan",
      email: "lucy-yzabelle.luklukan@stethomd.com",
      phoneNumber: "(656) 223-2221",
      extension: "113",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Scribe",
      department: "Remote",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "Monday-Saturday",
      preferredShiftTime: "8:00 AM - 2:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "Lucy Yzabelle Luklukan",
      notes: "Remote scribe schedule: Monday-Saturday.",
      strengths: "Scribe",
      schedulingPreferences: "Monday-Saturday",
      specialInstructions: ""
    },
    {
      staffId: "ST-028",
      fullName: "Omar Rabah",
      email: "omar.rabah@stethomd.com",
      phoneNumber: "(813) 666-2701",
      extension: "103",
      personalPhoneNumber: "Will be added by Fozia",
      jobTitle: "Staff",
      department: "Clinical",
      primarySpecialty: "None",
      officeLocation: "Tampa",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "Tampa June coverage",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Tampa",
      athenaUser: "orabah",
      notes: "Tampa: June 1, 2, 3, 8, 9, 13, 14, 15, 18, 19, 22, 25, 26, 29. Appears as Omar.",
      strengths: "",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-029",
      fullName: "Shahid Ali",
      email: "shahid.ali@stethomd.com",
      phoneNumber: "(321) 999-9553",
      extension: "-",
      personalPhoneNumber: "923216629665",
      jobTitle: "Billing Staff",
      department: "Billing",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "",
      preferredShiftTime: "8:00 AM - 5:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "sali357",
      notes: "",
      strengths: "Billing",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-030",
      fullName: "Rane Joseph",
      email: "rane.joseph@stethomd.com",
      phoneNumber: "(907) 318-9357",
      extension: "90001",
      personalPhoneNumber: "923317714336",
      jobTitle: "Billing Staff",
      department: "Billing",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-23",
      preferredWorkingDays: "",
      preferredShiftTime: "7:30 AM - 4:30 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "rjoseph120",
      notes: "",
      strengths: "Billing",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-031",
      fullName: "Usama Mazhar",
      email: "usama.mazhar@help360md.com",
      phoneNumber: "(813) 867-5753",
      extension: "111",
      personalPhoneNumber: "923196456257",
      jobTitle: "Billing Staff",
      department: "Billing",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2025-06-09",
      preferredWorkingDays: "",
      preferredShiftTime: "8:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "umazhar",
      notes: "Permanent administrator. PDF row displayed name as Usama Mazar; admin requirement uses Usama Mazhar.",
      strengths: "Billing",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-032",
      fullName: "Alan Wake",
      email: "alan.wake@stethomd.com",
      phoneNumber: "(907) 318-9357",
      extension: "90001",
      personalPhoneNumber: "923167430905",
      jobTitle: "Billing Staff",
      department: "Billing",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2025-06-09",
      preferredWorkingDays: "",
      preferredShiftTime: "7:30 AM - 4:30 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "awake1",
      notes: "",
      strengths: "Billing",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-033",
      fullName: "Muhammad Bilal",
      email: "muhammad.bilal@stethomd.com",
      phoneNumber: "(907) 318-9357",
      extension: "90001",
      personalPhoneNumber: "923046300825",
      jobTitle: "Coder",
      department: "Coding",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "",
      preferredShiftTime: "8:00 AM - 5:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "mbilal50",
      notes: "",
      strengths: "Coding",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-034",
      fullName: "Fozia Kanwal",
      email: "fozia.kanwal@stethomd.com",
      phoneNumber: "(813) 725-3186",
      extension: "106",
      personalPhoneNumber: "923000936529",
      jobTitle: "HR",
      department: "Administration",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-06-09",
      preferredWorkingDays: "",
      preferredShiftTime: "7:00 AM - 4:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "fkanwal1",
      notes: "Permanent administrator.",
      strengths: "HR",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-035",
      fullName: "Aimen Fatima",
      email: "aimen.fatima@stethomd.com",
      phoneNumber: "(813) 499-9300",
      extension: "107",
      personalPhoneNumber: "923212860286",
      jobTitle: "Scribe",
      department: "Remote",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2026-01-21",
      preferredWorkingDays: "",
      preferredShiftTime: "2:00 PM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "afatima24",
      notes: "",
      strengths: "Scribe",
      schedulingPreferences: "",
      specialInstructions: ""
    },
    {
      staffId: "ST-036",
      fullName: "Leon Kennedy",
      email: "leon.kennedy@stethomd.com",
      phoneNumber: "(907) 318-9357",
      extension: "90001",
      personalPhoneNumber: "923000936529",
      jobTitle: "Billing Staff",
      department: "Billing",
      primarySpecialty: "None",
      officeLocation: "Remote",
      timeZone: "EST",
      employmentStatus: "Active",
      verifiedDate: "2025-06-09",
      preferredWorkingDays: "",
      preferredShiftTime: "11:00 AM - 8:00 PM",
      maximumHoursPerWeek: "",
      availableLocations: "Remote",
      athenaUser: "lkennedy84",
      notes: "",
      strengths: "Billing",
      schedulingPreferences: "",
      specialInstructions: ""
    }
  ],
  schedules: {
    "2026-06": {
      Tampa: {
        location: "Tampa",
        month: "2026-06",
        footerNote: "Sabiha Office Team Lead Mondays through Thursdays 8:00AM to 6:00PM",
        days: {
          "2026-06-01": ["Shameka", "Harjun", "Sabiha", "Omar", "Rajeshwary (volunteer)"],
          "2026-06-02": ["Shameka", "Omar", "Ezinne", "Lillian"],
          "2026-06-03": ["Camilla", "Sabiha", "Omar", "Ezinne", "Rajeshwary (volunteer)"],
          "2026-06-04": ["Camilla", "Sabiha", "Ezinne", "Harjun"],
          "2026-06-05": ["Shameka", "Gabriel", "Sabiha", "Micole"],
          "2026-06-06": ["Camilla", "Gabriel", "Lillian", "Micole", "Rajeshwary (volunteer)"],
          "2026-06-07": ["Camilla", "Gabriel", "Lillian", "Micole"],
          "2026-06-08": ["Shameka", "Sabiha", "Omar", "Rajeshwary (volunteer)"],
          "2026-06-09": ["Shameka", "Omar", "Micole", "Nhyira"],
          "2026-06-10": ["Camilla", "Sabiha", "Micole", "Ezinne", "Nhyira"],
          "2026-06-11": ["Camilla", "Sabiha", "Ezinne", "Micole", "Nhyira"],
          "2026-06-12": ["Camilla", "Gabriel", "Sabiha", "Ezinne"],
          "2026-06-13": ["Shameka", "Gabriel", "Lillian", "Omar", "Rajeshwary (volunteer)"],
          "2026-06-14": ["Shameka", "Gabriel", "Lillian", "Omar"],
          "2026-06-15": ["Shameka", "Sabiha", "Omar", "Rajeshwary (volunteer)"],
          "2026-06-16": ["Shameka", "Sabiha", "Micole", "Nhyira"],
          "2026-06-17": ["Camilla", "Micole", "Ezinne", "Nhyira"],
          "2026-06-18": ["Camilla", "Sabiha", "Ezinne", "Micole", "Omar"],
          "2026-06-19": ["Shameka", "Nhyira", "Omar", "Ezinne"],
          "2026-06-20": ["Camilla", "Gabriel", "Lillian", "Rajeshwary (volunteer)"],
          "2026-06-21": ["Camilla", "Gabriel", "Lillian", "Sabiha"],
          "2026-06-22": ["Shameka", "Ezinne", "Sabiha", "Omar", "Rajeshwary (volunteer)"],
          "2026-06-23": ["Shameka", "Sabiha", "Micole", "Nhyira"],
          "2026-06-24": ["Camilla", "Sabiha", "Micole", "Nhyira"],
          "2026-06-25": ["Camilla", "Sabiha", "Micole", "Omar"],
          "2026-06-26": ["Camilla", "Nhyira", "Omar", "Ezinne"],
          "2026-06-27": ["Shameka", "Gabriel", "Lillian", "Rajeshwary (volunteer)"],
          "2026-06-28": ["Shameka", "Gabriel", "Lillian", "Ezinne"],
          "2026-06-29": ["Shameka", "Sabiha", "Omar", "Shayanne", "Rajeshwary (volunteer)"],
          "2026-06-30": ["Shameka", "Lillian", "Micole", "Nhyira"],
          "2026-07-01": ["Shameka", "Sabiha", "Micole", "Shayanne"],
          "2026-07-02": ["Camilla", "Sabiha", "Micole", "Nhyira"],
          "2026-07-03": ["Camilla", "Nhyira", "Omar", "Ezinne"],
          "2026-07-04": ["Camilla", "Omar", "Ezinne", "Rajeshwary (volunteer)"],
          "2026-07-05": ["Camilla", "Sabiha", "Ezinne", "Omar"]
        }
      },
      Zephyrhills: {
        location: "Zephyrhills",
        month: "2026-06",
        footerNote: "Monday to Friday - 7:30AM to 6PM, Saturday - 7:30AM to 2PM (Everyday Wednesday Dr. Rahman - Tampa)",
        days: {
          "2026-06-01": ["Camilla", "Aliana", "Carolyn (7:30AM-3PM)", "Shayanne", "Josephine (7:30AM-3:30PM)"],
          "2026-06-02": ["Dr. Rahman", "Sarai", "Gabi", "Carolyn (7:30AM-3PM)", "Anthony", "Josephine (7:30AM-3:30PM)"],
          "2026-06-03": ["Krish", "Sarai", "Anthony", "Shayanne", "Carolyn (7:30AM-3PM)", "Aliana (7:30AM-2PM)"],
          "2026-06-04": ["Krish", "Sarai", "Anthony", "Carolyn (7:30AM-3PM)", "Gabi (7:30AM-2PM)"],
          "2026-06-05": ["Dr. Rahman", "Sarai", "Gabi", "Aliana", "Carolyn (7:30AM-3PM)"],
          "2026-06-06": ["Dr. Rahman", "Aliana", "Gabi"],
          "2026-06-07": [],
          "2026-06-08": ["Dr. Rahman", "Aliana", "Carolyn (7:30AM-3PM)", "Shayanne", "Josephine (7:30AM-3:30PM)"],
          "2026-06-09": ["Dr. Rahman", "Sarai", "Gabi", "Carolyn (7:30AM-3PM)", "Anthony", "Alyssa", "Josephine (7:30AM-3:30PM)"],
          "2026-06-10": ["Dr. Rahman", "Sarai", "Anthony", "Shayanne", "Carolyn (7:30AM-3PM)", "Aliana (7:30AM-2PM)"],
          "2026-06-11": ["Dr. Rahman", "Sarai", "Anthony", "Carolyn (7:30AM-3PM)", "Gabi (7:30AM-2PM)"],
          "2026-06-12": ["Krish", "Sarai", "Gabi", "Aliana", "Carolyn (7:30AM-3PM)"],
          "2026-06-13": ["Krish", "Gabi", "Aliana"],
          "2026-06-14": [],
          "2026-06-15": ["Camilla", "Aliana", "Carolyn (7:30AM-3PM)", "Shayanne", "Josephine (7:30AM-3:30PM)"],
          "2026-06-16": ["Dr. Rahman", "Sarai", "Gabi", "Carolyn (7:30AM-3PM)", "Anthony", "Josephine (7:30AM-3:30PM)"],
          "2026-06-17": ["Krish", "Sarai", "Anthony", "Shayanne", "Carolyn (7:30AM-3PM)", "Aliana (7:30AM-2PM)"],
          "2026-06-18": ["Krish", "Sarai", "Anthony", "Carolyn (7:30AM-3PM)", "Gabi (7:30AM-2PM)"],
          "2026-06-19": ["Dr. Rahman", "Sarai", "Gabi", "Aliana", "Carolyn (7:30AM-3PM)"],
          "2026-06-20": ["Dr. Rahman", "Aliana", "Gabi"],
          "2026-06-21": [],
          "2026-06-22": ["Krish", "Josephine", "Aliana", "Carolyn (7:30AM-3PM)", "Josephine (7:30AM-3:30PM)"],
          "2026-06-23": ["Krish", "Sarai", "Gabi", "Carolyn (7:30AM-3PM)", "Anthony", "Josephine (7:30AM-3:30PM)"],
          "2026-06-24": ["Dr. Rahman", "Sarai", "Anthony", "Shayanne", "Carolyn (7:30AM-3PM)", "Aliana (7:30AM-2PM)"],
          "2026-06-25": ["Dr. Rahman", "Sarai", "Anthony", "Carolyn (7:30AM-3PM)", "Gabi (7:30AM-2PM)"],
          "2026-06-26": ["Krish", "Sarai", "Gabi", "Aliana", "Carolyn (7:30AM-3PM)"],
          "2026-06-27": ["Krish", "Aliana", "Gabi"],
          "2026-06-28": [],
          "2026-06-29": ["Camilla", "Aliana", "Carolyn (7:30AM-3PM)", "Josephine (7:30AM-3:30PM)"],
          "2026-06-30": ["Dr. Rahman", "Sarai", "Gabi", "Carolyn (7:30AM-3PM)", "Anthony", "Josephine (7:30AM-3:30PM)"],
          "2026-07-01": ["Dr. Rahman", "Sarai", "Anthony", "Carolyn (7:30AM-3PM)", "Aliana (7:30AM-2PM)"],
          "2026-07-02": ["Dr. Rahman", "Sarai", "Anthony", "Carolyn (7:30AM-3PM)", "Gabi (7:30AM-2PM)"],
          "2026-07-03": ["Dr. Rahman", "Sarai", "Gabi", "Aliana", "Carolyn (7:30AM-3PM)"],
          "2026-07-04": ["Dr. Rahman", "Aliana", "Gabi"],
          "2026-07-05": []
        }
      }
    }
  }
};
